### ISSUE TITLE
Able to add SASS font-loaders?

### ISSUE THREAD

**Issue by danjonesdev** [jesperorb/webpack-boilerplate#1]
So I've had a play around in webpack and even added "url-loader" yet I can't seem to get my fonts loaded using sass... Any ideas or possible implemnentations?

Thank you in advance
Dan

**Comment by jesperorb** [comment]
@danjonesdev Not sure, have not used this in combination with custom fonts loaded locally. Have you checked out this part of the `sass-loader` documentation: [https://github.com/webpack-contrib/sass-loader#problems-with-url](https://github.com/webpack-contrib/sass-loader#problems-with-url)

Might be that you have to change your paths to the fonts.

**Comment by danjonesdev** [comment]
@jesperorb  I tried using google fonts like so:

```
@font-face {
  font-family: "Anton";
  src: url('https://fonts.googleapis.com/css?family=Anton') format('truetype')
}
```

But it returns the following in my console:

> Failed to decode downloaded font: https://fonts.googleapis.com/css?family=Anton
> localhost/:1 OTS parsing error: invalid version tag

Which sucks, I've looked around endlessly online and can't seem to get around my problem.

Thanks
Dan

**Comment by jesperorb** [comment]
@danjonesdev If you just want to use google fonts there is no need to create your own `@font-face`. If you look inside the url (https://fonts.googleapis.com/css?family=Anton) you will see why. The fonts are already font-faces ready to use.

Just add this to the `<head>` in  `index.ejs` and the font will load:

```html
<link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
```
